{{- if .Values.ui.enabled }}
{{- $name := include "nightshift.fullname" (dict "Release" .Release "component" "nightshift-ui") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nightshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: nightshift-ui
spec:
  type: ClusterIP
  selector:
    {{- include "nightshift.selectorLabels" (dict "Release" .Release "component" "nightshift-ui") | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
{{- end }}
