{{- if .Values.minio.enabled }}
{{- $name := include "nightshift.minioFullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nightshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nightshift
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
      protocol: TCP
    {{- if .Values.minio.console.enabled }}
    - name: console
      port: {{ .Values.minio.console.port }}
      targetPort: {{ .Values.minio.console.port }}
      protocol: TCP
    {{- end }}
{{- end }}
