nav:
- index.md
- Anthropic: anthropic.md
- AWS Bedrock: aws-bedrock.md
- Azure AI Foundry: azure-ai-foundry.md
- Gemini: gemini.md
- GitHub Copilot: github-copilot.md
- GitHub Models: github.md
- Google Vertex AI: google-vertex-ai.md
- Ollama: ollama.md
- OpenRouter: openrouter.md
- OpenAI: openai.md
- OpenAI-Compatible: openai-compatible.md
- Other: other.md
- Robusta AI: robusta-ai.md
- Using Multiple Providers: using-multiple-providers.md
