nav:
  - index.md
  - Recommended Setup: recommended-setup.md
  - Built-in Toolsets: builtin-toolsets
  - HTTP Connectors: api-toolsets.md
  - Database Connectors: database-connectors.md
  - Custom Toolsets: custom-toolsets.md
  - MCP Servers: remote-mcp-servers.md
  - OAuth MCP Servers: oauth-mcp-servers.md
  - HTTP Header Propagation: header-propagation.md
