services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"

  grafana:
    image: grafana/grafana:11.1.0
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
