{{- if .Values.nightshift_api.worker.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nightshift_api.kube.workerServiceAccount }}
  namespace: {{ include "nightshift.workerNamespace" . }}
  labels:
    {{- include "nightshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: nightshift-worker
{{- end }}
