{{- if and .Values.createServiceAccount .Values.k8sRBAC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "holmes.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- toYaml .Values.serviceAccount.imagePullSecrets | nindent 2}}
{{- end }}
{{- end }}
