apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nightshift-api
  namespace: monitoring
  labels:
    app: nightshift-api
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: nightshift-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
