#!/usr/bin/env python3
"""Generate Terraform infrastructure files from templates."""

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

TEMPLATES_DIR = Path(__file__).parent.parent / "templates" / "terraform"

CLOUD_PLATFORMS = {
    "aws": "eks",
    "azure": "aks",
    "gcp": "gke",
}

DEFAULT_REGIONS = {
    "aws": "us-east-1",
    "azure": "eastus",
    "gcp": "us-central1",
}


def render_template(content: str, vars: dict) -> str:
    for key, value in vars.items():
        content = content.replace(f"{{{{{key}}}}}", str(value))
    return content


def copy_and_render_template(src: Path, dst: Path, vars: dict):
    dst.parent.mkdir(parents=True, exist_ok=True)
    content = src.read_text()
    rendered = render_template(content, vars)
    dst.write_text(rendered)


def generate_tfvars(output_dir: Path, vars: dict):
    lines = []
    for k, v in vars.items():
        if isinstance(v, str):
            lines.append(f'{k} = "{v}"')
        elif isinstance(v, bool):
            lines.append(f'{k} = {str(v).lower()}')
        else:
            lines.append(f'{k} = {v}')
    (output_dir / "terraform.tfvars").write_text("\n".join(lines) + "\n")


def run_terraform_validate(tf_dir: Path) -> tuple[bool, str]:
    """Run terraform fmt + validate (dry-run, no cloud creds needed)."""
    if not shutil.which("terraform"):
        return True, "terraform not in PATH, skipping validation"

    fmt = subprocess.run(["terraform", "fmt", "-recursive"], cwd=tf_dir, capture_output=True, text=True)
    validate = subprocess.run(
        ["terraform", "init", "-backend=false", "-input=false"],
        cwd=tf_dir, capture_output=True, text=True, timeout=60
    )
    if validate.returncode != 0:
        return False, validate.stderr
    validate2 = subprocess.run(
        ["terraform", "validate"],
        cwd=tf_dir, capture_output=True, text=True, timeout=30
    )
    return validate2.returncode == 0, validate2.stdout + validate2.stderr


def main():
    parser = argparse.ArgumentParser(description="Generate Terraform infrastructure files")
    parser.add_argument("--cloud", required=True, choices=["aws", "azure", "gcp"])
    parser.add_argument("--service", required=True, help="Service name (slug)")
    parser.add_argument("--use-case", default="web_app",
                        choices=["web_app", "microservice", "batch_job", "scheduled_task", "data_pipeline"])
    parser.add_argument("--region", help="Cloud region (defaults per cloud)")
    parser.add_argument("--env", default="dev", choices=["dev", "staging", "prod"])
    parser.add_argument("--output-dir", help="Where to write Terraform files (default: workspace/<service>/terraform)")
    parser.add_argument("--with-db", action="store_true", help="Include managed database")
    parser.add_argument("--with-redis", action="store_true", help="Include managed Redis/cache")
    parser.add_argument("--no-validate", action="store_true", help="Skip terraform validate")
    args = parser.parse_args()

    region = args.region or DEFAULT_REGIONS[args.cloud]
    platform = CLOUD_PLATFORMS[args.cloud]

    workspace = Path(__file__).parent.parent / "workspace"
    output_dir = Path(args.output_dir) if args.output_dir else workspace / args.service / "terraform"
    output_dir.mkdir(parents=True, exist_ok=True)

    template_dir = TEMPLATES_DIR / args.cloud
    if not template_dir.exists():
        print(json.dumps({"success": False, "error": f"No template for cloud: {args.cloud}"}))
        sys.exit(1)

    template_vars = {
        "SERVICE_NAME": args.service,
        "REGION": region,
        "ENVIRONMENT": args.env,
        "CLUSTER_NAME": f"{args.service}-{args.env}",
        "DB_NAME": args.service.replace("-", "_"),
        "PROJECT_ID": f"{args.service}-{args.env}",  # GCP project id placeholder
    }

    # Copy all .tf files from template
    resources_created = []
    for tf_file in template_dir.glob("**/*.tf"):
        rel = tf_file.relative_to(template_dir)
        dst = output_dir / rel
        copy_and_render_template(tf_file, dst, template_vars)
        resources_created.append(str(rel))
        print(f"[terraform_gen] Wrote {dst}")

    # Generate tfvars
    tfvars = {
        "service_name": args.service,
        "environment": args.env,
        "region": region,
        "cluster_name": f"{args.service}-{args.env}",
    }
    if args.cloud == "gcp":
        tfvars["project_id"] = f"{args.service}-{args.env}"
    generate_tfvars(output_dir, tfvars)
    resources_created.append("terraform.tfvars")

    # Write a README for the generated terraform
    readme = f"""# Terraform — {args.service} ({args.cloud.upper()})

Generated by devops-agent for **{args.use_case}** on {args.cloud.upper()}.

## Resources
- Kubernetes cluster ({platform.upper()}) in `{region}`
- Container registry
- Networking (VPC/VNET)
{"- Managed PostgreSQL" if args.with_db else ""}
{"- Managed Redis/Cache" if args.with_redis else ""}

## Deploy
```bash
cd {output_dir}
terraform init
terraform plan
terraform apply
```

## Environments
- dev: smallest/cheapest sizes, single AZ
- staging: mirrors prod sizing, multi-AZ
- prod: HA, multi-AZ, auto-scaling enabled
"""
    (output_dir / "README.md").write_text(readme)

    # Validate
    validate_ok, validate_msg = True, "skipped"
    if not args.no_validate:
        print(f"[terraform_gen] Running terraform fmt + validate...")
        validate_ok, validate_msg = run_terraform_validate(output_dir)
        status = "passed" if validate_ok else "FAILED"
        print(f"[terraform_gen] Validation {status}: {validate_msg}")

    print(json.dumps({
        "success": True,
        "terraform_dir": str(output_dir),
        "cloud": args.cloud,
        "platform": platform,
        "region": region,
        "environment": args.env,
        "resources_created": resources_created,
        "validation": {"ok": validate_ok, "message": validate_msg},
    }))


if __name__ == "__main__":
    main()
