{{- if .Values.ui.enabled }}
{{- $name := include "nightshift.fullname" (dict "Release" .Release "component" "nightshift-ui") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nightshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: nightshift-ui
{{- end }}
